[project]
name = "audio-artifacts-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.127.0",
    "librosa>=0.11.0",
    "onnx>=1.20.0",
    "onnxruntime>=1.23.2",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
]

[tool.ruff]
line-length = 200
target-version = "py312"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E", "W",
    # flake8-2020
    "YTT",
    # flake8-bugbear
    "B",
    # flake8-quotes
    "Q",
    # flake8-debugger
    "T10",
    # flake8-gettext
    "INT",
    # flake8-pytest-style
    "PT",
    # flake8-pyi
    "PYI",
    # flake8-type-checking
    "TC",
    # Ruff-specific rules
    "RUF",
    # flake8-bandit: exec-builtin
    "S102",
    # flake8-logging-format
    "G",
    # flake8-future-annotations
    "FA",
    # flake8-slots
    "SLOT",
    # flake8-raise
    "RSE"
]


[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
quote-style = "double"

[tool.pytest.ini_options]
pythonpath = "."
testpaths = "tests"
markers = [
    "utils: tests for utils functions",
]
